# Generated by Django 4.2 on 2023-04-20 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=64, null=True, verbose_name='User Name')),
                ('first_name', models.CharField(max_length=256, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name goods')),
                ('seasonal', models.BooleanField(default=False, verbose_name='Сезонная вещь')),
                ('week_tariff', models.IntegerField(default=0, verbose_name='Storage price per week')),
                ('month_tariff', models.IntegerField(default=0, verbose_name='Storage price per month')),
            ],
            options={
                'verbose_name': 'Stored item',
                'verbose_name_plural': 'Stored items',
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=1024, null=True, unique=True, verbose_name='Warehouse Address')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='1', max_length=100, unique=True, verbose_name='Order number')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('seasonal_store', models.BooleanField(default=False, verbose_name='Seasonal items')),
                ('other_type_size', models.IntegerField(default=0, null=True, verbose_name='Cell size')),
                ('seasonal_goods_count', models.IntegerField(null=True, verbose_name='Number of seasonal items')),
                ('store_duration', models.IntegerField(null=True, verbose_name='Duration of storage')),
                ('store_duration_type', models.CharField(choices=[('0', 'week'), ('1', 'month')], default='0', max_length=1, verbose_name='Unit of storage time')),
                ('cost', models.FloatField(default=0, verbose_name='Storage cost')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='selfstoragebot.goods', verbose_name='Stored item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='selfstoragebot.clients', verbose_name='Client')),
                ('warehouse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='selfstoragebot.warehouses', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
