# Generated by Django 4.2 on 2023-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstoragebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_status',
            field=models.CharField(choices=[('0', 'Создан'), ('1', 'В работе'), ('2', 'Ожидает доставки'), ('3', 'Курьер в пути'), ('4', 'Груз на складе'), ('5', 'Возвращен')], db_index=True, default=0, max_length=15, null=True, verbose_name='Статус доставки заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='type_delivery',
            field=models.CharField(choices=[('0', 'Самостоятельно'), ('1', 'Курьером')], db_index=True, max_length=15, null=True, verbose_name='Тип доставки'),
        ),
    ]
