# Generated by Django 4.2 on 2023-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstoragebot', '0002_orders_delivery_status_orders_type_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=255, unique=True)),
                ('click_count', models.IntegerField(default=0)),
            ],
        ),
    ]
