# Generated by Django 4.2 on 2023-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstoragebot', '0002_clients_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
    ]
