# Generated by Django 4.2 on 2023-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstoragebot', '0003_invitationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Администратор'),
        ),
    ]
