# Generated by Django 4.2 on 2023-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstoragebot', '0005_alter_orders_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_to',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address of returning'),
        ),
    ]
